export default {
  login: 'uncrownedthrone',
  id: 52833074,
  node_id: 'MDQ6VXNlcjUyODMzMDc0',
  avatar_url: 'https://avatars.githubusercontent.com/u/52833074?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/uncrownedthrone',
  html_url: 'https://github.com/uncrownedthrone',
  followers_url: 'https://api.github.com/users/uncrownedthrone/followers',
  following_url:
    'https://api.github.com/users/uncrownedthrone/following{/other_user}',
  gists_url: 'https://api.github.com/users/uncrownedthrone/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/uncrownedthrone/starred{/owner}{/repo}',
  subscriptions_url:
    'https://api.github.com/users/uncrownedthrone/subscriptions',
  organizations_url: 'https://api.github.com/users/uncrownedthrone/orgs',
  repos_url: 'https://api.github.com/users/uncrownedthrone/repos',
  events_url: 'https://api.github.com/users/uncrownedthrone/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/uncrownedthrone/received_events',
  type: 'User',
  site_admin: false,
  name: 'Justin S.',
  company: 'Avado Enterprises',
  blog: 'uncrownedthrone.com',
  location: 'Tampa, Florida',
  email: null,
  hireable: true,
  bio: 'react dev [ ☕️ ] dog person [  fan ]\r\n',
  twitter_username: 'uncrownedthrone',
  public_repos: 59,
  public_gists: 0,
  followers: 4,
  following: 7,
  created_at: '2019-07-12T16:28:14Z',
  updated_at: '2022-04-29T20:26:15Z',
}
